### ISSUE TITLE
Fails with non-default setting of redis

### ISSUE THREAD

**Issue by hamukazu** [SPSCommerce/redlock-py#19]
Hello,

I ran redis on port number 9000, and tried to use redlock-py then it failed. It reproduces with the following code:

``` python
import redlock

rl = redlock.Redlock({"host": "localhost", "port": 9000})
lock = rl.lock("test", 100)
rl.unlock(lock)
```

and the following is the error message I get:

```
ERROR:root:Error unlocking resource test in server StrictRedis<ConnectionPool<Connection<host=None,port=6379,db=0>>>
Traceback (most recent call last):
  File "/home/kato/.pyenv/versions/3.5.1/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/kato/.pyenv/versions/3.5.1/lib/python3.5/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/kato/.pyenv/versions/3.5.1/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused
```

It looks it is looking at the default port when it tries to lock.

**Comment by hamukazu** [comment]
I solved it by myself looking at the source code. The argument should be specified as list of dict, not a dict. Changing the third line with

```
rl = redlock.Redlock([{"host": "localhost", "port": 9000}])
```

then it works.
