### ISSUE TITLE
Lock method does not work

### ISSUE THREAD

**Issue by RafaelAcostaQ2** [SPSCommerce/redlock-py#20]
Hi,
I'm not sure what am I doing wrong but I haven't being able to use this package. It is exactly what I need but for some reason it throws an error when I try to lock a resource.

redis_version:2.4.10

python version 3.5.2

This is my code

>>> from  redlock import Redlock
>>> dlm = Redlock([{"host": "REDIS_SERVER_IP", "port": 6379,  "db": 0}, ])

Acquire lock for 1 minute

>>> my_lock = dlm.lock("this_is_my_key",1000)

ERROR:root:Error unlocking resource this_is_my_key in server StrictRedis<ConnectionPool<Connection<host=X.X.X.X,port=6379,db=0>>>
Traceback (most recent call last):
  File "/home/redis/apps/Proj/env/lib/python3.5/site-packages/redlock/__init__.py", line 80, in unlock_instance
    server.eval(self.unlock_script, 1, resource, val)
  File "/home/redis/apps/Proj/env/lib/python3.5/site-packages/redis/client.py", line 1932, in eval
    return self.execute_command('EVAL', script, numkeys, *keys_and_args)
  File "/home/redis/apps/Proj/env/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/redis/apps/Proj/env/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/redis/apps/Proj/env/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'EVAL'

Thanks in advanced!

**Comment by NadiaSama** [comment]
Hi my english is not very well.
It seems the version of your redis server is too low you should update it to v2.6.0 or later.[EVAL command](https://redis.io/commands/eval)

**Comment by jheld** [comment]
Can this result in a different raised exception? Something to the tune of your version of redis-server is too old?
